---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels: 
    app.kubernetes.io/instance: test-oct15
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-oct15 
  name: test-oct15
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi